### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'state_is_tuple'

### ISSUE THREAD

**Issue by keplersj** [crazydonkey200/tensorflow-char-rnn#3]
Was trying to experiment with this in the TensorFlow Docker image and got this back after running `ython train.py --data_file=data/tiny_shakespeare.txt --test`:

```
============================================================
All final and intermediate outputs will be stored in output/
All information will be logged to stdout
============================================================

03:43:22 INFO:Parameters are:
{
    "batch_size": 20, 
    "dropout": 0.0, 
    "embedding_size": 0, 
    "hidden_size": 128, 
    "input_dropout": 0.0, 
    "learning_rate": 0.002, 
    "max_grad_norm": 5.0, 
    "model": "lstm", 
    "num_layers": 2, 
    "num_unrollings": 10
}

03:43:22 INFO:Reading data from: data/tiny_shakespeare.txt
03:43:22 INFO:Number of characters: 1000
03:43:22 INFO:Creating train, valid, test split
03:43:22 INFO:Creating vocabulary
03:43:22 INFO:Vocabulary is saved in output/vocab.json
03:43:22 INFO:Vocab size: 46
03:43:22 INFO:Creating graph
Traceback (most recent call last):
  File "train.py", line 373, in <module>
    main()
  File "train.py", line 241, in main
    train_model = CharRNN(is_training=True, use_batch=True, **params)
  File "/src/char_rnn_model.py", line 66, in __init__
    **params)
TypeError: __init__() got an unexpected keyword argument 'state_is_tuple'
```

**Comment by crazydonkey200** [comment]
The code now works fine with >=TensorFlow 1.1. So closing the issue :)
